# Generated by Django 5.0.7 on 2024-09-16 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('store', '0005_remove_order_customer_remove_order_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='checkout.transaction'),
        ),
    ]
